### ISSUE TITLE
TypeError: URL is not a constructor :(

### ISSUE THREAD

**Issue by muellerberndt** [ConsenSysDiligence/armlet#105]
After #104, armlet still errors in the browser at the same line as before:

```
module.exports.defaultApiUrl = new URL(defaultApiUrl)
```

This time the error is:

```
Uncaught TypeError: URL is not a constructor
```

Which is surprising because URL is supposed to be a built-in class and I'm convinced I had it working exactly like that. Tested in Safari and Chrome.

**Comment by muellerberndt** [comment]
Just found [this StackOverflow answer](https://stackoverflow.com/questions/54546419/uncaught-typeerror-url-is-not-a-constructor-in-javascript). Maybe the URL variable is overwritten somewhere?

I also tried this code in the browser (it works):

```
<html>
<head>

<script>

var URL
URL = URL || require('url').URL

var url = new URL("https://www.google.com");

console.log(url);

</script>
```

**Comment by muellerberndt** [comment]
Also, for reference, this is the context where I'm getting the exception:

https://github.com/aquiladev/remix-ide/tree/mythx

**Comment by muellerberndt** [comment]
@nbanmp is this code necessary?

```
var URL
URL = URL || require('url').URL
```

This is what seems to break the remix-ide, it works when removed.

**Comment by birdofpreyru** [comment]
@b-mueller my guess is that you need:
```
var URL
URL = (typeof window !== 'undefined' && window.URL)
  ? window.URL : require('url').URL
```

**Comment by muellerberndt** [comment]
Yep, that works.

**Comment by vdenisov-pro** [comment]
Here is an example of this error occurring.

1) In the first file `Twilio.js` (name not important) an attempt is made to call the `URL` class from the `url` library
( `var url = require ('url');` ).

2) The second file `url.d.ts` (which stores types for the `url` library) has a description for the `URL` class.
So when you write `new url.Url` linter does not swear, because the class being called is described in the typing.
This usually means that the library has similar functionality.

... but not this time ...

3) In the third file `url.js` (where the basic logic for the `url` library is described) the `URL` class is missing.
And this is why the error occurs. As a result, the `url.URL` is not a constructor or function or anything else.
It's just `undefined`.

P.S.:
* note the paths to these files (for each file, it is indicated in small font under the name)
* do not pay attention to the fact that I show an error in the example `Twilio.js`
(is a case from my problem, but it shows a General problem).

![twilio-URL-problem](https://user-images.githubusercontent.com/31067728/90056052-f210d680-dce6-11ea-9e35-f3356a057ef3.png)

**Comment by javiermendozain** [comment]
This work for me:

Change this: 
` var URL = window.URL;`

By this:
```
function URL(url, base) {
  this.url = url;
  this.base = base;
  return window.URL;
}
```

on file `node_modules/recordrtc/RecordRTC.js`

I did with that script on package 
``` "postinstall": "cp patch/RecordRTC.js node_modules/recordrtc/RecordRTC.js"```

**Comment by hiepxanh** [comment]
tested with angular 14 SSR, you should lazy load it to prevent it leak to override global namespace URL of nodejs (mention here https://github.com/muaz-khan/RecordRTC/issues/666)

dont have to hack in node_modules


``` .ts
        let RecordRTC;
        let moduleRecord;
        await this.ngZone.run(async () => {
          // https://stackoverflow.com/a/58859327/5748537
          moduleRecord = await import('recordrtc');
          RecordRTC = (moduleRecord as any).default;
        });

        this.record = new RecordRTC(this.stream, {
          mimeType: 'audio/wav',
          type: 'audio',
          numberOfAudioChannels: 1,
          disableLogs: true,
          desiredSampRate: 12000,
          recorderType: RecordRTC.StereoAudioRecorder,
        }); 
```







 do you love me?
