### ISSUE TITLE
Switch from "standard" to "eslint" for lint checking? 

### ISSUE THREAD

**Issue by rocky** [ConsenSysDiligence/armlet#6]

**Comment by daniyarchambylov** [comment]
@rocky could you please clarify why there is a need to change standard to eslint? Do you want to switch to Eslint, so that eventually we could have custom eslint plugin for all projects? 

There is already a package with eslint config that works like standard: https://github.com/standard/eslint-config-standard

We can just use this as a base plugin or create .eslintrc with all the rules required for standard linting.

Please let me know how you want this issue to be resolved.

**Comment by rocky** [comment]
What's there now is fine.
